### ISSUE TITLE
HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by iPeterPan** [MrSyee/dl_apps#7]
올리주신대로 patch 를 했는데도 오류가 나는군요.
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
[<ipython-input-23-1dacb717d12a>](https://localhost:8080/#) in <cell line: 1>()
----> 1 streams = yt.streams.filter(progressive=True, file_extension="mp4", type="video").order_by("resolution").desc()
      2 for stream in streams:
      3     print(stream)

12 frames
[/usr/lib/python3.10/urllib/request.py](https://localhost:8080/#) in http_error_default(self, req, fp, code, msg, hdrs)
    641 class HTTPDefaultErrorHandler(BaseHandler):
    642     def http_error_default(self, req, fp, code, msg, hdrs):
--> 643         raise HTTPError(req.full_url, code, msg, hdrs, fp)
    644 
    645 class HTTPRedirectHandler(BaseHandler):

HTTPError: HTTP Error 400: Bad Request
![image](https://github.com/user-attachments/assets/41485d90-ce59-4609-bb15-b2810e315ff3)

**Comment by MrSyee** [comment]
안녕하세요. 해당 문제 확인하였습니다.
pytube가 현재 업데이트가 되고 있지 않아 pytubefix라는 라이브러리가 새롭게 사용되고 있어 예제도 그걸로 변경하려합니다.

패치 라인과 import를 수정하면 동작하는 것을 확인해서 수정 예정입니다.
```
!pip install pytubefix==7.1.3

from pytubefix import YouTube
```

![image](https://github.com/user-attachments/assets/52708ff9-1769-47ed-a1f5-ed8f5ce585f7)

**Comment by MrSyee** [comment]
commit https://github.com/MrSyee/dl_apps/commit/4906e63be68625ddfbae023ba68c240db1a9b74d 에서 처리하였습니다.
